avatars
TourMind/tourmind pull request #119
Opened 2023-05-16 11:30 UTC by chencac

2023-05-21 05:34 UTC, cacachang requested changes

2023-05-21 05:34 UTC, cacachang commented on app/controllers/users/registrations_controller.rb
> +    def account_register_params
請問 account_register_params 跟 sign_up_params 有啥差別？
名字看起來都是註冊用的，但裡面要求的參數不一樣

2023-05-21 05:34 UTC, cacachang commented on app/views/shared/_navbar.html.erb
>            <img src="<%= current_user.avatar_url %>" alt="avatar" class = "w-10 h-10 rounded-full">
可用 image_tag

2023-05-21 05:43 UTC, yangliang0514 commented on app/controllers/users/registrations_controller.rb
> +    def account_register_params
account_register_params是舊的 已經刪掉的
dev裡面應該已經沒有這個東西
這裡是解衝突沒有解正確吧

2023-05-21 06:41 UTC, YuTingLan commented on app/views/shared/_navbar.html.erb
>            <img src="<%= current_user.avatar_url %>" alt="avatar" class = "w-10 h-10 rounded-full">
這個問題在user img re-flash page issues PR做修正，會改成
<img src="<%= asset_path('user_default_avatar.png') %>" alt="avatar" class="w-10 h-10 rounded-full">

2023-05-23 06:36 UTC, YuTingLan commented
上傳大頭照無法即時渲染，有空再修正
不點照片其實不知道可以上傳照片，是否可以加個註解？（上傳大頭照之類的）

2023-05-23 06:37 UTC, YuTingLan approved these changes

2023-05-23 10:00 UTC, Hsubetty approved these changes

2023-05-23 16:07 UTC, yangliang0514 approved these changes

2023-05-23 23:42 UTC, CCTWeng approved these changes

2023-05-24 01:57 UTC, merged