Search
TourMind/tourmind pull request #120
Opened 2023-05-16 11:31 UTC by chencac

首頁搜尋，餐廳、景點、飯店搜尋使用者搜尋項目消失

2023-05-17 13:03 UTC, Hsubetty commented
建議:小tag文字會縮可調整
<img width="1483" alt="截圖 2023-05-17 下午9 03 17" src="https://github.com/TourMind/tourmind/assets/123808430/82d9e951-2336-466f-a454-2b2e76e1e725">

2023-05-17 13:03 UTC, Hsubetty approved these changes

2023-05-20 11:42 UTC, YuTingLan commented
RWD會順便做嗎？有時間的話，可以之後再開一張票做

（有時間做的話）可以考慮用劃線的方式區分類別小卡，保持風格統一～
![截圖 2023-05-20 下午7 36 11](https://github.com/TourMind/tourmind/assets/127638342/45c4fa8e-93c8-47b1-afe4-949a1f4fa40c)
![截圖 2023-05-20 下午7 36 19](https://github.com/TourMind/tourmind/assets/127638342/24a191b6-46f3-436c-b011-382db9047796)

2023-05-20 11:45 UTC, YuTingLan approved these changes

2023-05-20 12:18 UTC, CCTWeng approved these changes

2023-05-20 13:46 UTC, chencac commented
> RWD會順便做嗎？有時間的話，可以之後再開一張票做
> 
> （有時間做的話）可以考慮用規劃線的方式區分類別小卡，保持風格統一～ ![截圖 2023-05-20 下午7 36 11](https://user-images.githubusercontent.com/127638342/239685062-45c4fa8e-93c8-47b1-afe4-949a1f4fa40c.png) ![截圖 2023-05-20 下午7 36 19](https://user-images.githubusercontent.com/127638342/239685065-24a191b6-46f3-436c-b011-382db9047796.png)

我一起做

2023-05-20 14:06 UTC, yangliang0514 commented on app/views/page/search.html.erb
> +      <%= form_with(url: page_search_path, method: "get", id: "search-form", data: { controller: "search", action: "submit->search.clearInput" }, class: "flex justify-center mb-2 max-h-10") do |form|
action: "submit->search.clearInput"
這個寫法是有作用的嗎？

2023-05-21 06:21 UTC, cacachang requested changes

2023-05-21 06:21 UTC, cacachang commented on app/controllers/page_controller.rb
>    helper_method :star_rating
這東西應該要放到 view helper

2023-05-21 06:21 UTC, cacachang commented on config/routes.rb
>    get '/404', to: "application#record_not_found"
這不用特別寫出來吧？ 還記得在 application_controller 只要 raise record_not_found 他就會自己去找 404 頁面

2023-05-21 06:21 UTC, cacachang commented on app/views/page/_restaurant.html.erb
> +                <img class="w-full h-full object-cover" src="<%= restaurant.images.first.url %>" alt="Restaurant Pic">
我有點疑問為什麼上面用 img tag 下面用 image_tag？
看要不要統一

2023-05-21 06:21 UTC, cacachang commented on app/views/page/search.html.erb
> +      <section data-favorite-target="section" data-section="restaurant" class="justify-between items-center hidden">
下面這區塊是要做啥的？ 感覺跟上面重複但又 hidden 了

2023-05-21 06:21 UTC, cacachang commented on app/views/page/_restaurant.html.erb
> +            <%= link_to restaurants_path(restaurant_type: [restaurant.restaurant_type]) do %>
這樣寫有點怪， path 後面的參數應該都是加 id，query 應該都要另外設定
可以參考一下[這篇](https://stackoverflow.com/questions/2695538/add-querystring-parameters-to-link-to)

2023-05-21 06:21 UTC, cacachang commented on app/views/page/_restaurant.html.erb
> +                    <%= link_to restaurants_path(cuisine_types: [cuisine_type]) do %>
同上

2023-05-21 06:21 UTC, cacachang commented on app/views/page/_restaurant.html.erb
> +                    <%= link_to restaurants_path(atmostphere: [atmostphere]) do %>
同上

2023-05-21 06:34 UTC, yangliang0514 commented on config/routes.rb
>    get '/404', to: "application#record_not_found"
這個是我寫的
是因為行程有些是前端處理完
再打到後端
開這一條是如果前端有出錯
也可以跳轉到404畫面
還是有更好的作法？

2023-05-21 13:04 UTC, yangliang0514 approved these changes

2023-05-23 06:38 UTC, merged