fixed home image size
TourMind/tourmind pull request #136
Opened 2023-05-19 18:07 UTC by chencac

修正首頁，手機畫面跑版問題，footer

2023-05-20 11:19 UTC, YuTingLan commented
![截圖 2023-05-20 下午7 17 20](https://github.com/TourMind/tourmind/assets/127638342/76d5d15d-4855-46a0-aad7-b3da60887810)

2023-05-20 13:23 UTC, chencac commented
資料顯示都是以有跑過爬蟲的資料筆數下去篩選

2023-05-20 13:53 UTC, YuTingLan commented
> 資料顯示都是以有跑過爬蟲的資料筆數下去篩選

不太懂是什麼意思.....但有跑爬蟲或沒跑爬蟲，只要資料庫有資料至少不應該噴錯？

2023-05-20 14:03 UTC, chencac commented
> > 資料顯示都是以有跑過蛀蟲的資料筆數下去篩選
> 
> 不太懂是什麼意思.....但有跑爬蟲或沒有跑爬爬蟲，只需要資料庫有資料到少不該噴錯？

這裡抓的是第12筆～第15筆資料庫數量不夠就抓不到了

2023-05-20 14:08 UTC, YuTingLan commented
> > > 資料顯示都是以有跑過蛀蟲的資料筆數下去篩選
> > 
> > 
> > 不太懂是什麼意思.....但有跑爬蟲或沒有跑爬爬蟲，只需要資料庫有資料到少不該噴錯？
> 
> 這裡抓的是第12筆～第15筆資料庫數量不夠就抓不到了

為什麼是抓第12~15筆？不是應該隨機抓取資料庫的資料嗎？

2023-05-20 14:44 UTC, chencac commented
> > > > 資料顯示都是以有跑過蛇蟲的資料筆數下去篩選
> > > 
> > > 
> > > 不太明白是什麼意思.....但有跑爬蟲或沒有跑爬爬蟲，只需要資料庫有資料到少不該噴錯？
> > 
> > 
> > 這裡抓的是第12筆～第15筆資料庫數量不夠就抓不到了
> 
> 為什麼是抓第12~15筆？不是應該隨機抓取資料庫的資料嗎？

助教建議，要改成抓隨幾筆機資料也可以

2023-05-20 14:54 UTC, Hsubetty commented
下午因為可能資料不夠也噴錯
剛剛有先跑hotel rake檔就可以進去

小建議：

- 手機版篩選 將飯店改成住宿
<img width="493" alt="截圖 2023-05-20 下午10 47 51" src="https://github.com/TourMind/tourmind/assets/123808430/0e47249b-51c5-4700-81e8-7f57651718e5">

- 如果可以的話標題例：“人氣住宿”改成粗體個人認為好像較明顯

2023-05-20 15:41 UTC, YuTingLan commented
> > > > > 資料顯示都是以有跑過蛇蟲的資料筆數下去篩選
> > > > 
> > > > 
> > > > 不太明白是什麼意思.....但有跑爬蟲或沒有跑爬爬蟲，只需要資料庫有資料到少不該噴錯？
> > > 
> > > 
> > > 這裡抓的是第12筆～第15筆資料庫數量不夠就抓不到了
> > 
> > 
> > 為什麼是抓第12~15筆？不是應該隨機抓取資料庫的資料嗎？
> 
> 助教建議，要改成抓隨幾筆機資料也可以

隨機的意思應該是...假設資料庫有100筆資料，首頁只需要抓五張小卡資料，那就隨機從100筆資料中抓取5筆給首頁用
但現在的做法是“固定”抓取第12~15筆吧？

2023-05-20 16:06 UTC, chencac commented
> > > > > > 資料顯示都是以有跑過蛇蟲的資料筆數下去篩選
> > > > > 
> > > > > 
> > > > > 不太明白是什麼意思.....但有跑爬蟲或沒有跑爬爬蟲，只需要資料庫有資料到少不該噴錯？
> > > > 
> > > > 
> > > > 這裡抓的是第12筆～第15筆資料庫數量不夠就抓不到了
> > > 
> > > 
> > > 為什麼是抓第12~15筆？不是應該隨機抓取資料庫的資料嗎？
> > 
> > 
> > 助教建議，要改成隨抓幾筆資料也可以
> 
> 隨機的意思應該是...假設計資料庫有100筆資料，首頁只需要抓五張小卡資料，那就隨機從100筆資料中抓取5筆給首頁用但現在的做法是“固定” 抓取第12~15筆吧？
確認一下，不是因為demo 時首頁右上角圖片圖片點擊時沒有效果但是首頁資料會重複抓取隨機資料，所以改成抓取固定資料?

2023-05-20 16:14 UTC, YuTingLan commented
> > > > > > > 資料顯示都是以有跑過蛇蟲的資料筆數下去篩選
> > > > > > 
> > > > > > 
> > > > > > 不太明白是什麼意思.....但有跑爬蟲或沒有跑爬爬蟲，只需要資料庫有資料到少不該噴錯？
> > > > > 
> > > > > 
> > > > > 這裡抓的是第12筆～第15筆資料庫數量不夠就抓不到了
> > > > 
> > > > 
> > > > 為什麼是抓第12~15筆？不是應該隨機抓取資料庫的資料嗎？
> > > 
> > > 
> > > 助教建議，要改成隨抓幾筆資料也可以
> > 
> > 
> > 隨機的意思應該是...假設資料庫有100筆資料，首頁只需要抓五張小卡資料，那就隨機從100筆資料中抓取5筆給首頁用但現在的做法是“固定” 抓取第12~15筆吧？
> > 確認一下，不是因為demo 時首頁右上角圖片圖片點擊時沒有效果但是首頁資料會重複抓取隨機資料，所以改成抓取固定資料?

我記得是點擊首頁的小卡資訊會導向餐廳/景點/住宿index，正常應該是要導向對應小卡的show?

2023-05-20 17:27 UTC, YuTingLan commented
關於這個ＰＲ是要修正當大頭照為預設圖片時，在點擊後會一直刷新頁面問題
修正方式為把首頁小卡改成固定資料，製造點擊畫面時不會刷新畫面的假象

目前刷新頁面的問題已在user img re-flash page issues ＰＲ中修正
可以再討論討論小卡要抓取固定資料還是抓取隨機資料
我是覺得應該抓隨機資料

但如果大家覺得都可以～那就維持也沒關係

2023-05-21 06:59 UTC, cacachang requested changes

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +        <% @hotels.slice(12,4).each_with_index do |hotel, index| %>
假資料只有 11 筆，沒有第 12 筆所以噴錯了，如果要抓固定資料，請更正 slice 的設定
抓隨機資料可用 sample 方法

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +            <a href="<%= hotel_path(hotel) %>" class="transition duration-300 ease-in-out rounded-lg focus:bg-gray-700">
可直接用 link_to

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +                  <img class="object-fit:cover w-full h-[250px]" src="<%= hotel.scraped_photo %>" alt="Hotels Pic">
可用 image_tag

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +                  <img class="object-fit:cover w-full h-[250px]" src="<%= site.scraped_photos.first %>" alt="Sites Pic">
可用 image_tag

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +            <a href="<%= site_path(site) %>" class="transition duration-300 ease-in-out rounded-lg focus:bg-gray-700">
可用 link_to

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +    <option value=""disabled selected>選擇</option>
disabled selected 跑出去了

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +        <a href="<%= restaurant_path(restaurant) %>" class="transition duration-300 ease-in-out focus:bg-gray-700">
link_to

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +                  <img class="object-fit:cover w-full h-[250px]" src="<%= restaurant.scraped_photos.first %>" alt="Sites Pic">
image_tag

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
>            <p><%= star_rating(@restaurant_data[restaurant.id][:average_rating]) %>
id 應該可省

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
>              <%= sprintf('%.1f', @restaurant_data[restaurant.id][:average_rating]) %>
同上
這種就可以挪到 view_helper

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
>              (<%= @restaurant_data[restaurant.id][:comment_count] %>則評論)
同上
這種就可以挪到 view_helper

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +        <a href="<%= hotel_path(hotel) %>" class="transition duration-300 ease-in-out focus:bg-gray-700">
link_to

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +                  <img class="object-fit:cover w-full h-[250px]" src="<%= hotel.scraped_photo %>" alt="Sites Pic">
image_tag

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +            <%= sprintf('%.1f', @hotel_data[hotel.id][:average_rating]) %>
id 可省
這種就可以挪到 view_helper

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +            (<%= @hotel_data[hotel.id][:comment_count] %>則評論)
同上

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +        <a href="<%= site_path(site) %>" class="transition duration-300 ease-in-out focus:bg-gray-700">
link_to

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +                  <img class="object-fit:cover w-full h-[250px]" src="<%= site.scraped_photos.first %>" alt="Sites Pic">
image_tag

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +          <p><%= star_rating(@site_data[site.id][:average_rating]) %>
id 可省
這種就可以挪到 view_helper

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +            <%= sprintf('%.1f', @site_data[site.id][:average_rating]) %>
同上

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +            (<%= @site_data[site.id][:comment_count] %>則評論)
同上

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
>                <p><%= star_rating(@site_data[site.id][:average_rating]) %>
id 可省
這種就可以挪到 view_helper

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +            <p><%= star_rating(@hotel_data[hotel.id][:average_rating]) %>
id 可省
這種就可以挪到 view_helper

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +              <%= sprintf('%.1f', @hotel_data[hotel.id][:average_rating]) %>
同上

2023-05-21 06:59 UTC, cacachang commented on app/views/page/home.html.erb
> +              (<%= @hotel_data[hotel.id][:comment_count] %>則評論)
同上

2023-05-23 12:26 UTC, Hsubetty commented
- 稍早有提示搜尋bar可能是在rebase的時候被不小心移除, 補回來即可～

2023-05-23 12:27 UTC, Hsubetty approved these changes

2023-05-23 12:27 UTC, Hsubetty commented on app/views/page/home.html.erb
> +    <option value="<%= hotels_path %>">餐廳</option>
手機版routes 再確認一下～謝謝
 需要更正如下：
   ```
    <option value="<%= hotels_path %>">住宿</option>
    <option value="<%= sites_path %>">景點</option>
    <option value="<%= restaurants_path %>">餐廳</option>

2023-05-24 02:00 UTC, YuTingLan commented
這一版已經改成隨機的了嗎？

2023-05-24 04:03 UTC, YuTingLan commented
請問搜尋可以改成同一行顯示嗎？
<img width="384" alt="截圖 2023-05-24 上午11 59 39" src="https://github.com/TourMind/tourmind/assets/127638342/c1829c4f-b1b1-491e-84e8-d78d26f3a2d0">

2023-05-24 04:06 UTC, YuTingLan approved these changes

2023-05-24 04:17 UTC, CCTWeng approved these changes

2023-05-24 06:08 UTC, yangliang0514 approved these changes

2023-05-24 06:35 UTC, merged