Comment
TourMind/tourmind pull request #3
Opened 2023-04-25 03:31 UTC by chencac

2023-04-25 14:44 UTC, cacachang requested changes

2023-04-25 14:44 UTC, cacachang commented on Gemfile
> +  gem 'web-console', '>= 4.1.0'
下面已經有一個 `web-console`

2023-04-25 14:44 UTC, cacachang commented on Gemfile
> +gem "tailwindcss-rails", "~> 2.0"
上面也有 `tailwind` 了

2023-04-25 14:44 UTC, cacachang commented on Gemfile
> +gem "hotwire-rails", "~> 0.1.3"
上面也有 `hotwire-rails`

2023-04-25 14:44 UTC, cacachang commented on app/controllers/comments_controller.rb
> +    def new
縮排

2023-04-25 14:44 UTC, cacachang commented on app/controllers/comments_controller.rb
> +      @comments = Comment.by_content(params[:keyword])
keyword 要不要改 content ？ 這樣看不出來要搜尋什麼

2023-04-25 14:44 UTC, cacachang commented on app/models/comment.rb
> +  validates :content, presence: true
`comment` 只需要 `content` 存在就好嗎？
`title` 跟 `author` 沒有也沒關係嗎

2023-04-25 14:44 UTC, cacachang commented on db/schema.rb
> +    t.json "images"
end 在哪兒

2023-04-25 14:44 UTC, cacachang commented on db/schema.rb
> +    t.datetime "updated_at", precision: 6, null: false
end 在哪兒？

2023-04-25 14:44 UTC, cacachang commented on app/views/comments/index.html.erb
> +  <div class="flex-shrink-0 w-full md:w-1/2 p-4">
縮排

2023-04-25 14:44 UTC, cacachang commented on app/views/comments/index.html.erb
> +          <% rating = comment.rating %>
為什麼要在 view 裡面定義？

2023-04-25 14:44 UTC, cacachang commented on app/views/comments/_form.html.erb
> +        <div class="w-2/5">
標題跟評論好像相反了？

2023-04-26 04:18 UTC, yangliang0514 approved these changes

2023-04-26 14:20 UTC, chencac commented on app/views/comments/index.html.erb
> +  <div class="flex-shrink-0 w-full md:w-1/2 p-4">
已修正

2023-04-27 15:17 UTC, CCTWeng approved these changes

2023-04-27 15:17 UTC, CCTWeng commented on db/schema.rb
> +
country應該是第一版的欄位 已由city取代

2023-04-27 22:37 UTC, Hsubetty approved these changes

2023-04-28 12:51 UTC, YuTingLan commented
上傳圖片後是不是應該顯示小圖？ 顯示超大圖有點怪
mini_magick 和 imagemagick-binaries不是有套件嗎？ 
<img width="966" alt="截圖 2023-04-28 下午8 51 20" src="https://user-images.githubusercontent.com/127638342/235152426-cb87ac03-b12a-4f1f-b4d4-6be46c9580aa.png">
<img width="966" alt="截圖 2023-04-28 下午8 51 20" src="https://user-images.githubusercontent.com/127638342/235152440-5acb19a2-4e0e-4565-a319-714745830383.png">

為什麼還要另外下載ImageMagick在本機才可以正常顯示小圖？再麻煩確認一下？

2023-04-28 12:58 UTC, YuTingLan commented
1. 星星中間有圓點，是ＢＵＧ嗎？
<img width="136" alt="截圖 2023-04-28 下午8 52 29" src="https://user-images.githubusercontent.com/127638342/235152729-65c99a79-9158-49d7-acf2-0e401215c58f.png">

2. 標題跟評論有加驗證，那是不是要順便顯示一下錯誤提示或錯誤訊息？
3. 現在背景會自動偵測本機的主色系顯示對應的顏色，再修改一下預色值？
<img width="939" alt="截圖 2023-04-28 下午8 56 12" src="https://user-images.githubusercontent.com/127638342/235153812-34397623-b364-4887-aabe-7e15449daa6c.png">

2023-04-28 13:13 UTC, YuTingLan commented
4. 評論會再加上時間戳記嗎？

備註： 因為之前user有bug，在註冊時username無法寫入資料庫，這個問題我昨天已經修正完成，等待大家第一次合併完成，我再送ＰＲ，你之後再記得放上userID～謝謝

2023-04-29 02:03 UTC, YuTingLan approved these changes

2023-04-29 07:21 UTC, merged