Sites CRUD
TourMind/tourmind pull request #31
Opened 2023-04-25 08:21 UTC by Hsubetty

Sites model

2023-04-25 10:44 UTC, Hsubetty commented
因為剛剛驗證有點小問題～所以原版先關閉

2023-04-26 18:06 UTC, cacachang requested changes

2023-04-26 18:06 UTC, cacachang commented on db/migrate/20230425075326_fix_column_name.rb
> +    rename_column :hotels, :equipment_types, :equipment
Rails Guide或[方法](https://api.rubyonrails.org/v7.0.4.2/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_column)看清楚怎麼用喔，我跑 db:migrate 下去就壞了

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/85012510/234647964-8d058b0c-0eae-44da-9b9b-20f3919c3d2d.png">

2023-04-26 18:06 UTC, cacachang commented on app/controllers/hotels_controller.rb
> +                                  :hotel_type, equipment: [])
是 `hotel_types` 吧？

2023-04-26 18:06 UTC, cacachang commented on app/views/hotels/index.html.erb
> +  <!--小於768px會出現的按鈕區塊--->
html.erb 應該不能有這種註解出現喔

2023-04-26 18:06 UTC, cacachang commented on app/views/hotels/show.html.erb
> +      <%=@hotel.hotel_type%>
`hotel_types`

2023-04-26 18:06 UTC, cacachang commented on app/controllers/hotels_controller.rb
> +    @hotel_equipment = @hotels.map do |hotel|
不太懂這邊撈出來然後又去看他是否存在的意義是什麼

2023-04-26 18:06 UTC, cacachang commented on app/controllers/sites_controller.rb
> +    @site_type = @sites.map do |site|
同 hotel

2023-04-26 18:06 UTC, cacachang commented on app/views/hotels/index.html.erb
> +                  <% if @hotel_equipment[index].present? %>
可以直接寫成 `<% if hotel.equipment.present? %>`

2023-04-26 18:06 UTC, cacachang commented on app/views/hotels/index.html.erb
> +                      <% @hotel_equipment[index].each do |equipment| %>
跟著上方 feedback，這邊就要改成`<% hotel.equipment.each do |equipment| %>`

2023-04-26 18:06 UTC, cacachang commented on app/views/hotels/index.html.erb
> +<%= render 'shared/navbar' %>
看起來沒跑過 rubocop

2023-04-26 18:06 UTC, cacachang commented on app/controllers/hotels_controller.rb
> +      render :new, status: :unprocessable_entity
用 rails 6 應該不用加 `status: :unprocessable_entity` 也可以渲染出錯誤訊息

參考文件：https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission

2023-04-26 18:06 UTC, cacachang commented on app/views/shared/_footer.html.erb
> +<footer class="flex justify-center p-2 bg-white">
現在網站上沒看到喔

2023-04-26 18:06 UTC, cacachang commented on app/controllers/sites_controller.rb
> +      render :new, status: :unprocessable_entity
用 rails 6 應該不用加 `status: :unprocessable_entity` 也可以渲染出錯誤訊息

參考文件：https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission

2023-04-26 18:06 UTC, cacachang commented on app/helpers/hotels_helper.rb
> +module HotelsHelper
沒用到可刪

2023-04-26 18:06 UTC, cacachang commented on app/helpers/sites_helper.rb
> +module SitesHelper
沒用到可刪

2023-04-26 18:06 UTC, cacachang commented on app/views/sites/_form.html.erb
> +        <% site_types=%w[大自然 歷史 藝文 購物 戶外 海邊 森林] %>
試試看用這個[方法](https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-collection_check_boxes) `collection_check_boxes`

2023-04-26 18:06 UTC, cacachang commented on app/views/sites/index.html.erb
> +                  <% if @site_type[index].present? %>
應該可以直接用 site 抓吧？
可參考 hotel index 的 feedback，看起來做法是一樣的

2023-04-26 18:06 UTC, cacachang commented on app/javascript/controllers/hotel_controller.js
> +    const icon = event.currentTarget.children[0];
icon 用 `data-target` 試試

2023-04-26 18:06 UTC, cacachang commented on app/javascript/controllers/hotel_controller.js
> +    const filterOptions = event.currentTarget.nextElementSibling;
同上

2023-04-27 06:55 UTC, Hsubetty commented on db/migrate/20230425075326_fix_column_name.rb
> +    rename_column :hotels, :equipment_types, :equipment
4/27助教協助解決:
由於本地資料庫欄位與夥伴不相容
rails db:drop ->清空db column 
rails db:create -> 把目前的欄位都抓進去我的schema 
rails g migrate rename_equipment_types_to_equipment 執行用migration需要修改的欄位
rails db:migrate

2023-04-27 06:57 UTC, Hsubetty commented on app/controllers/hotels_controller.rb
> +                                  :hotel_type, equipment: [])
index and show 修正為hotel_types

2023-04-27 06:57 UTC, Hsubetty commented on app/views/hotels/index.html.erb
> +  <!--小於768px會出現的按鈕區塊--->
已刪除不正確註解

2023-04-27 12:12 UTC, Hsubetty commented on app/views/hotels/show.html.erb
> +      <%=@hotel.hotel_type%>
已修正

2023-04-27 12:22 UTC, Hsubetty commented on app/controllers/hotels_controller.rb
> +    @hotel_equipment = @hotels.map do |hotel|
已修正

2023-04-27 12:22 UTC, Hsubetty commented on app/views/sites/index.html.erb
> +                  <% if @site_type[index].present? %>
已修正

2023-04-28 03:38 UTC, YuTingLan commented
1. 目前搜尋功能只能搜名稱跟地址，能在提示文字上提醒使用者只能獲這兩個欄位的搜尋嗎？或者之後改成可以搜尋整個資料庫？
2. 這個是devise套件造成語系是英文，之後需要在config >>> locales 寫中文版
<img width="570" alt="截圖 2023-04-28 上午11 23 51" src="https://user-images.githubusercontent.com/127638342/235047753-456e651b-517f-4430-93ad-ae2f187f006c.png">
3. sites show 沒有放name
4. site 有放上傳照片，hotel 沒有放，之後記得整合一下

2023-04-28 03:54 UTC, yangliang0514 approved these changes

2023-04-28 04:16 UTC, CCTWeng approved these changes

2023-04-28 04:16 UTC, CCTWeng commented on app/views/hotels/index.html.erb
> +              <%= @hotels.count %> 家物業
應該印出全部飯店而不是只有那頁的飯店
可以用kaminari的total_count

2023-04-28 04:16 UTC, CCTWeng commented on app/views/hotels/index.html.erb
> +        <% @hotels.each_with_index do |hotel, index| %>
沒用到index的話 可以用.each就好

2023-04-28 04:16 UTC, CCTWeng commented on app/views/sites/index.html.erb
> +            <%= @sites.count %> 個景點
使用 total_count

2023-04-28 04:16 UTC, CCTWeng commented on app/views/sites/index.html.erb
> +        <% @sites.each_with_index do |site, index| %>
用each就好

2023-04-28 04:16 UTC, CCTWeng commented on app/views/sites/index.html.erb
縮版

2023-04-28 04:16 UTC, CCTWeng commented on app/views/sites/show.html.erb
> +          class: 'mt-2 rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium' , data: { confirm: '您確定要刪除這個景點嗎？' } %>
縮版

2023-04-28 04:49 UTC, YuTingLan commented on app/assets/stylesheets/application.tailwind.css
> +
13~18 沒用到，可以刪除

2023-04-28 04:49 UTC, YuTingLan commented on app/assets/stylesheets/application.tailwind.css
> +}
47~50 沒有用到請刪除

2023-04-28 04:49 UTC, YuTingLan commented on app/assets/stylesheets/application.tailwind.css
> +}
52~54 沒有用到請刪除

2023-04-28 04:49 UTC, YuTingLan commented on app/assets/stylesheets/application.tailwind.css
> +
請確認一下是不是沒有用到？ 我在程式裡面搜尋不到 btn-form

2023-04-28 04:49 UTC, YuTingLan commented on app/javascript/controllers/index.js
> +application.register("navbar", NavbarController)
第8行沒用到  可以刪掉

2023-04-28 04:49 UTC, YuTingLan commented on app/javascript/controllers/navbar_controller.js
> +}
navbar_controller.js   這個資料夾沒用到，可以刪除？

2023-04-28 04:49 UTC, YuTingLan commented on app/javascript/scripts/fontawesome.js
> +dom.watch()
faHeartPulse, faPencil, faLocationDot, faRightToBracket, faCrown, faBars 這些沒用到可以刪除

2023-04-28 04:49 UTC, YuTingLan commented on app/javascript/scripts/fontawesome.js
> +dom.watch()
第四行一樣

2023-04-28 04:49 UTC, YuTingLan commented on app/views/hotels/_form.html.erb
> +    <%= form.text_field :tel, class:'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2
這應該可以用tel_field？

2023-04-28 04:49 UTC, YuTingLan commented on app/views/hotels/_form.html.erb
> +    <%= form.text_field :star_rating, class:'block shadow rounded-md border border-gray-200 outline-none px-3 py-2
這是不是用number_field？

2023-04-28 04:49 UTC, YuTingLan commented on app/views/hotels/_form.html.erb
> +    <%= form.text_field :image, class:'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2
改 file_field ？ 或是 url_field？

2023-04-28 04:49 UTC, YuTingLan commented on app/views/shared/_footer.html.erb
> +</footer>
_footer.html.erb  這個柏陞寫了？  要不要先整個砍掉？

2023-04-28 04:49 UTC, YuTingLan commented on app/views/shared/_navbar.html.erb
> +</nav>
這張票已轉移給別人做，那就先整段移除噢～  或者整個資料夾刪除，避免後面還要解衝突

2023-04-28 04:49 UTC, YuTingLan commented on app/views/sites/_form.html.erb
> +        <%= form.text_field :tel, class:'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2
應該可以改成電話欄位？

2023-04-28 04:49 UTC, YuTingLan commented on app/views/sites/index.html.erb
> +              <% end %>
縮排是錯的吧？

2023-04-28 04:49 UTC, YuTingLan commented on app/views/sites/index.html.erb
> +                <span class="text-red-500 text-3xl">&#x2665;</span>
愛心功能之後記得要跟喜愛清單做連結

2023-04-28 04:49 UTC, YuTingLan commented on app/views/layouts/application.html.erb
> +    <link rel=”stylesheet” href=”css/font-awesome.css” class="fa-solid fa-heart-pulse">
link 是不是可以刪除  這應該算在導覽列的票？

2023-04-28 06:22 UTC, Hsubetty commented on app/assets/stylesheets/application.tailwind.css
> +
已刪除

2023-04-28 06:22 UTC, Hsubetty commented on app/assets/stylesheets/application.tailwind.css
> +}
已刪除

2023-04-28 06:23 UTC, Hsubetty commented on app/assets/stylesheets/application.tailwind.css
> +}
已刪除

2023-04-28 06:27 UTC, Hsubetty commented on app/assets/stylesheets/application.tailwind.css
> +
已刪除

2023-04-28 06:29 UTC, Hsubetty commented on app/views/layouts/application.html.erb
> +    <link rel=”stylesheet” href=”css/font-awesome.css” class="fa-solid fa-heart-pulse">
已刪除

2023-04-28 06:29 UTC, Hsubetty commented on app/views/sites/index.html.erb
> +                <span class="text-red-500 text-3xl">&#x2665;</span>
ＯＫ！

2023-04-28 13:36 UTC, Hsubetty commented on app/views/sites/_form.html.erb
> +        <%= form.text_field :tel, class:'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2
已修改為form.telephone_field

2023-04-28 13:39 UTC, Hsubetty commented on app/javascript/controllers/index.js
> +application.register("navbar", NavbarController)
已刪除

2023-04-28 13:40 UTC, Hsubetty commented on app/assets/stylesheets/application.tailwind.css
> +
field_with_errors textarea 有使用tailwind在form 故先不刪除

2023-04-28 13:42 UTC, Hsubetty commented on app/views/sites/index.html.erb
> +        <% @sites.each_with_index do |site, index| %>
已調整

2023-04-28 13:42 UTC, Hsubetty commented on app/views/sites/index.html.erb
> +            <%= @sites.count %> 個景點
已調整

2023-04-28 13:42 UTC, Hsubetty commented on app/views/hotels/index.html.erb
> +        <% @hotels.each_with_index do |hotel, index| %>
已調整

2023-04-28 13:42 UTC, Hsubetty commented on app/views/hotels/index.html.erb
> +              <%= @hotels.count %> 家物業
已調整

2023-04-28 13:43 UTC, Hsubetty commented on app/views/sites/index.html.erb
已跑rubocop希望沒問題～

2023-04-28 13:43 UTC, Hsubetty commented on app/views/shared/_navbar.html.erb
> +</nav>
已刪除nabar and footer

2023-04-28 13:45 UTC, Hsubetty commented on app/views/sites/_form.html.erb
> +        <% site_types=%w[大自然 歷史 藝文 購物 戶外 海邊 森林] %>
此方法後續等優化切版時試試～目前先推暫定的PR

2023-04-28 13:45 UTC, Hsubetty commented on app/javascript/controllers/hotel_controller.js
> +    const icon = event.currentTarget.children[0];
此方法後續等優化切版時試試～目前先推暫定的PR

2023-04-28 15:06 UTC, YuTingLan approved these changes

2023-04-28 15:06 UTC, YuTingLan commented on config/environments/development.rb
>    }
為什麼要加逗號？

2023-04-28 15:06 UTC, YuTingLan commented on config/environments/development.rb
>      }
為什麼要加逗號？

2023-04-28 15:06 UTC, YuTingLan commented on config/environments/test.rb
>    }
逗號？

2023-04-28 15:06 UTC, YuTingLan commented on config/spring.rb
>  )
逗號？

2023-04-28 15:06 UTC, YuTingLan commented on app/models/restaurant.rb
這是改到別人的程式嗎？要不要跟全政確認一下？

2023-04-28 15:48 UTC, Hsubetty commented on app/models/restaurant.rb
已確認dev全政的code
在新的commit 修復rubocop前的樣子

2023-04-28 15:49 UTC, Hsubetty commented on config/spring.rb
>  )
應為rubocop的建議
印象中應不影響功能～

2023-04-29 02:37 UTC, chencac approved these changes

2023-04-29 08:24 UTC, cacachang requested changes

2023-04-29 08:24 UTC, cacachang commented on Gemfile
第 82 跟 83 行請刪掉，重複的 gem "carrierwave" "mini_magick"

2023-04-29 08:24 UTC, cacachang commented on app/controllers/hotels_controller.rb
> +      redirect_to hotel_path(@hotel.id), notice: '更新成功!'
可簡寫 `redirect_to hotel_path(@hotel)`

2023-04-29 08:24 UTC, cacachang commented on app/views/hotels/index.html.erb
> +                      <% hotel.equipment.each do |equipment| %>
你的 equipment 是字串格式，不能用 each，會直接噴錯

2023-04-29 08:24 UTC, cacachang commented on test/application_system_test_case.rb
> +# frozen_string_literal: true
沒用到就刪

2023-04-29 08:24 UTC, cacachang commented on app/views/hotels/show.html.erb
> +    <% @hotel.equipment.each do |equipment| %>
同上

2023-04-29 08:24 UTC, cacachang commented on app/controllers/sites_controller.rb
> +    flash.now[:alert] = '沒有找到符合條件的景點' and return if @sites.empty?
景點沒資料的時候，點進 index 頁面就會跳出沒有找到符合條件的景點，可留著之後優化

2023-04-29 12:36 UTC, cacachang approved these changes

2023-04-29 12:36 UTC, cacachang commented on app/models/hotel.rb
> +  validates :name, :tel, :address, presence: true
網址 / 電話 之後可以做個格式驗證，前端有的話會更好

2023-04-29 12:36 UTC, cacachang commented on app/models/site.rb
> +  validates :name, :tel, :address, presence: true
同上

2023-04-29 13:04 UTC, merged